//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык приложения.
        /// </summary>
        public static string AppLanguageText {
            get {
                return ResourceManager.GetString("AppLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Города.
        /// </summary>
        public static string CitiesText {
            get {
                return ResourceManager.GetString("CitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чёрный.
        /// </summary>
        public static string ColorBlack {
            get {
                return ResourceManager.GetString("ColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синий.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коричневый.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розовый.
        /// </summary>
        public static string ColorPink {
            get {
                return ResourceManager.GetString("ColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красный.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиолетовый.
        /// </summary>
        public static string ColorViolet {
            get {
                return ResourceManager.GetString("ColorViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string FileNamePostfix {
            get {
                return ResourceManager.GetString("FileNamePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста.
        /// </summary>
        public static string FontColorText {
            get {
                return ResourceManager.GetString("FontColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер текста.
        /// </summary>
        public static string FontSizeText {
            get {
                return ResourceManager.GetString("FontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта.
        /// </summary>
        public static string LatitudeText {
            get {
                return ResourceManager.GetString("LatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота.
        /// </summary>
        public static string LongitudeText {
            get {
                return ResourceManager.GetString("LongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string MapText {
            get {
                return ResourceManager.GetString("MapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погодные аномалии отсутствуют.
        /// </summary>
        public static string NoWeatherReported {
            get {
                return ResourceManager.GetString("NoWeatherReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки погоды.
        /// </summary>
        public static string WeatherLoadErrorMessage {
            get {
                return ResourceManager.GetString("WeatherLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление ветра.
        /// </summary>
        public static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
    }
}
